name: 'Pick up Jura ticket ID Action'
description: "Pick up Jira ticket ID from commit comment and combine as PR's comment"
author: 'tyankatsu0105'
inputs:
  JIRA_CLIENT_PROTOCOL:
    required: false
    default: 'https'
  JIRA_CLIENT_HOST:
    required: true
  JIRA_CLIENT_USERNAME:
    required: false
  JIRA_CLIENT_PASSWORD:
    required: false
    default: '2'
  JIRA_CLIENT_API_VERSION:
    required: false
    default: 'true'
runs:
  using: 'node12'
  main: 'dist/index.js'
