name: Release
on:
  pull_request:
    types:
      - closed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check branch name
        id: check-branch
        run: |
          if [[ ${{ github.head_ref }} =~ v[0-9]+.[0-9]+.[0-9]+ ]]; then
              echo ::set-output name=match::true
          fi

      - name: Publish Tag
        if: steps.check-branch.outputs.match == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ github.head_ref }}
          git push origin ${{ github.head_ref }}
